name: Cypress-DownloadFile Test

on: push
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build:all            
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
            name: videos
            path: cypress/videos